// <auto-generated />
using IdentityClaims.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IdentityClaims.Migrations
{
    [DbContext(typeof(IdentityClaimsContext))]
    partial class IdentityClaimsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityClaims.Models.Lookup", b =>
                {
                    b.Property<int>("LookupID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActiveFlag")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<string>("Attribute1")
                        .HasMaxLength(128);

                    b.Property<string>("Attribute2")
                        .HasMaxLength(128);

                    b.Property<string>("Attribute3")
                        .HasMaxLength(128);

                    b.Property<string>("Attribute4")
                        .HasMaxLength(128);

                    b.Property<string>("Attribute5")
                        .HasMaxLength(128);

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(48);

                    b.Property<string>("LookupDesc")
                        .IsRequired()
                        .HasMaxLength(48);

                    b.HasKey("LookupID");

                    b.ToTable("Lookup");
                });

            modelBuilder.Entity("IdentityClaims.Models.LookupValue", b =>
                {
                    b.Property<int>("LookupValueID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActiveFlag")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<string>("Attribute1")
                        .HasMaxLength(128);

                    b.Property<string>("Attribute2")
                        .HasMaxLength(128);

                    b.Property<string>("Attribute3")
                        .HasMaxLength(128);

                    b.Property<string>("Attribute4")
                        .HasMaxLength(128);

                    b.Property<string>("Attribute5")
                        .HasMaxLength(128);

                    b.Property<int>("LookupID");

                    b.Property<string>("LookupValueCode")
                        .IsRequired()
                        .HasMaxLength(48);

                    b.Property<string>("LookupValueDesc")
                        .IsRequired()
                        .HasMaxLength(48);

                    b.HasKey("LookupValueID");

                    b.HasIndex("LookupID");

                    b.ToTable("LookupValue");
                });

            modelBuilder.Entity("IdentityClaims.Models.LookupValue", b =>
                {
                    b.HasOne("IdentityClaims.Models.Lookup", "Lookup")
                        .WithMany("LookupValues")
                        .HasForeignKey("LookupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
